version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:14.4-browsers
    working_directory: ~/rockygray.com
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/rockygray.com
  node_modules:
    docker:
      - image: circleci/node:14.4-browsers
    working_directory: ~/rockygray.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:14.4-browsers
    working_directory: ~/rockygray.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Package
          command: make build
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/rockygray.com/build
  deploy:
    machine:
      enabled: true
    working_directory: ~/rockygray.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy the app
          command: make publish
workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout
      - node_modules:
          requires:
            - checkout
      - build:
          requires:
            - node_modules
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
